const mongoose = require("mongoose");

const socialPostSchema = new mongoose.Schema(
  {
    caption: {
      type: String,
      required: [true, "Caption is required"],
      trim: true,
    },
    imageUrl: {
      type: String,
      default: "",
      trim: true,
    },
    hashtags: {
      type: [String],
      default: [],
    },
    platforms: {
      type: [String],
      enum: ["facebook", "instagram", "linkedin"],
      required: true,
    },

    accountIds: {
      type: [String],
      default: [],
    },

    postType: {
      type: String,
      enum: ["image", "carousel", "reel"],
      default: "image",
    },
    mediaUrls: {
      type: [String],
      default: [],
    },
    videoUrl: { type: String, default: "" },
    coverImageUrl: { type: String, default: "" },

    scheduledAt: {
      type: Date,
      required: true,
    },
    scheduledBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    status: {
      type: String,
      enum: [
        "DRAFT",
        "PENDING_APPROVAL",
        "APPROVED",
        "REJECTED",
        "SCHEDULED",
        "POSTING",
        "POSTED",
        "PARTIALLY_POSTED",
        "FAILED",
      ],
      default: "DRAFT",
    },

    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    approvedAt: { type: Date, default: null },
    approvalNote: { type: String, default: "" },
    rejectedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    rejectedAt: { type: Date, default: null },
    rejectionReason: { type: String, default: "" },

    facebookPostId: { type: String, default: "" },
    instagramPostId: { type: String, default: "" },
    linkedinPostId: { type: String, default: "" },
    postedAt: { type: Date, default: null },
    failureReason: { type: String, default: "" },

    // "autopilot" = generated by services/autopilotService.js
    source: { type: String, enum: ["manual", "autopilot"], default: "manual" },

    // The Autopilot campaign that made this post (models/AutopilotCampaign.js).
    campaignId: { type: mongoose.Schema.Types.ObjectId, ref: "AutopilotCampaign", default: null },

    // What an autopilot post was made from, so it can be revised on the owner's feedback.
    autopilotMeta: {
      imagePrompt: { type: String, default: "" },
      topic: { type: String, default: "" },
      angle: { type: String, default: "" },
      captionBrief: { type: String, default: "" },
      revising: { type: Boolean, default: false },
      revisions: { type: Number, default: 0 },
      revisionError: { type: String, default: "" },
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Tenant",
      default: null,
    },
  },
  { timestamps: true },
);

socialPostSchema.index({ status: 1 });
socialPostSchema.index({ scheduledAt: 1 });
socialPostSchema.index({ createdAt: -1 });
socialPostSchema.index({ tenantId: 1 });
socialPostSchema.index({ tenantId: 1, source: 1, scheduledAt: 1 });
socialPostSchema.index({ tenantId: 1, campaignId: 1, source: 1 });

module.exports = mongoose.model("SocialPost", socialPostSchema);
